### ISSUE TITLE
update files from boilerplate

### ISSUE THREAD

**Issue by nunodotferreira** [flovan/headstart-boilerplate#3]
Hi

is there a way of doing an update to my boilerplate files like:

headstart init --update or headstart init --base --update gituser/repo

even if i already have created my project?

**Comment by flovan** [comment]
Sure thing. You can find a step-by-step on the [upgrading page](http://www.headstart.io/upgrading.html).
It's not the easiest of things to do if you're unfamiliar with the command line, but I hope I explained if well enough for people to follow.
If not, [I'm open to suggestions](https://github.com/flovan/headstart-website/issues).

EDIT: Oops, closed by accident.

**Comment by flovan** [comment]
@nunodotferreira did you manage to update your project/boilerplate? I'm checking off some issues and I'd like to close this one if you did.

**Comment by nunodotferreira** [comment]
yes i did. It's working fine.
